#Travis CI configuration for MAP-Tk
# See http://travis-ci.org/Kitware/maptk/

sudo: false

language: cpp

matrix:
  include:
    - compiler: gcc
      env:
        - C_COMPILER=gcc-4.8
        - CXX_COMPILER=g++-4.8
    - compiler: clang
      env: # default clang is version 3.4
        - C_COMPILER=clang
        - CXX_COMPILER=clang++

cache:
  directories:
  - $HOME/deps
  - /opt/kitware

before_script:
  - bash .travis/install-deps.sh

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libgl1-mesa-dev
    - libxt-dev
    - libqt4-dev
    - python-sphinx

script:
  - export PATH=$HOME/deps/bin:$PATH
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$C_COMPILER
          -DCMAKE_CXX_COMPILER=$CXX_COMPILER
          -DCMAKE_INSTALL_PREFIX=$HOME/install
          -DMAPTK_ENABLE_GUI:BOOL=ON
          -DMAPTK_ENABLE_TESTING:BOOL=ON
          -DMAPTK_SUPERBUILD:BOOL=OFF
          ../
  - make -j2
  - make install
  - ctest
